networks:
  backend:
    driver: bridge
    internal: true
  frontend:
    driver: bridge

services:
  redis:
    image: docker.io/library/redis:latest
    container_name: redis
    command: redis-server
    networks:
      - backend
    restart: unless-stopped

  app:
    image: docker.io/library/gradle:jdk21
    container_name: app
    working_dir: /app
    volumes:
      - .:/app
      - gradle-cache:/home/gradle/.gradle
    command: ./gradlew run
    ports:
      - "0.0.0.0:8080:8080"
    networks:
      - backend
      - frontend
    environment:
      CACHE_URI: redis://redis/
      GOOGLE_MAPS_API_KEY_FILE: secrets/google-maps-api-key
      JWT_SECRET_FILE: secrets/jwt-secret
      RATE_LIMIT_DEFAULT: ${RATE_LIMIT_DEFAULT}
      RATE_LIMIT_LOGIN: ${RATE_LIMIT_LOGIN}
      RATE_LIMIT_REGISTER: ${RATE_LIMIT_REGISTER}
      RATE_LIMIT_UNVERIFIED: ${RATE_LIMIT_UNVERIFIED}
      RATE_LIMIT_VERIFIED: ${RATE_LIMIT_VERIFIED}
      STATUS_API_TOKEN_HASH_FILE: secrets/status-api-token-hash
    depends_on:
      - redis
    restart: unless-stopped

volumes:
  gradle-cache:
