ktor {
    deployment {
        host =  "127.0.0.1"
        port = 8080
    }
    application {
        dependencies = [
            net.geoshare_app.CacheKt.provideCache,
            net.geoshare_app.CertificateRevocation.provideCertificateRevocation,
            net.geoshare_app.CertificateVerification.provideCertificateVerification,
            net.geoshare_app.GoogleMapsClientKt.provideGoogleMapsClient,
        ]
        modules = [
            net.geoshare_app.ApplicationKt.rootModule,
            net.geoshare_app.AuthenticationKt.authenticationModule,
            net.geoshare_app.AdminKt.adminModule,
            net.geoshare_app.GoogleMapsKt.googleMapsModule,
        ]
    }
}

auth {
    challenge {
        expireSec = 120
    }
    device {
        expireSec = 7776000
    }
    jwt {
        expireSec = 86400
        secret = ${JWT_SECRET}
    }
}

cache {
    uri = ${CACHE_URI}
}

googleMaps {
    apiKeyFile = ${GOOGLE_MAPS_API_KEY_FILE}
}

jwt {
    secret = ${JW_SECRET}
    expireSec = 86400
}
