ktor {
    deployment {
        host =  "127.0.0.1"
        port = 8080
    }
    application {
        dependencies = [
            net.geoshare_app.CacheKt.provideCache,
            net.geoshare_app.GoogleMapsClientKt.provideGoogleMapsClient,
        ]
        modules = [
            net.geoshare_app.ApplicationKt.rootModule,
            net.geoshare_app.AuthenticationKt.authenticationModule,
            net.geoshare_app.GoogleMapsKt.googleMapsModule,
        ]
    }
}

cache {
    uri = ${CACHE_URI}
}

database {
    url = ${DATABASE_URL}
    driver = "org.postgresql.Driver"
    user = ${DATABASE_USER}
}

googleMaps {
    apiKeyFile = ${GOOGLE_MAPS_API_KEY_FILE}
}

jwt {
    secret = ${JW_SECRET}
}
