ktor {
    deployment {
        host =  "127.0.0.1"
        port = 8080
    }
    application {
        modules = [
            net.geoshare_app.DatabaseKt.configureDatabase,
            net.geoshare_app.ApplicationKt.rootModule,
            net.geoshare_app.GoogleMapsKt.googleMapsModule,
        ]
    }
}

database {
    url = ${DATABASE_URL}
    driver = "org.postgresql.Driver"
    user = ${DATABASE_USER}
    password = ${DATABASE_PASSWORD}
}
