ktor {
    deployment {
        host =  "127.0.0.1"
        port = 8080
    }
    application {
        dependencies = [
            net.geoshare_app.CacheKt.provideCache,
            net.geoshare_app.CertificateVerificationKt.provideCertificateVerification,
            net.geoshare_app.DemoGoogleMapsClientKt.provideDemoGoogleMapsClient,
        ]
        modules = [
            net.geoshare_app.ApplicationKt.rootModule,
            net.geoshare_app.AuthenticationKt.authenticationModule,
            net.geoshare_app.GoogleMapsKt.googleMapsModule,
        ]
    }
}

auth {
    challengeExpireSec = 120
    deviceExpireSec = 7776000
    jwtExpireSec = 86400
    jwtSecretFile = ${JWT_SECRET_FILE}
    revocationListRefreshIntervalSec = 86400
}

cache {
    uri = ${CACHE_URI}
}

googleMaps {
    apiKeyFile = ${GOOGLE_MAPS_API_KEY_FILE}
    statusApiKeyHashFile = ${STATUS_API_KEY_HASH_FILE}
}

rateLimit {
    defaultLimit = 100
    defaultRefillPeriodSec = 60
    loginLimit = 100
    loginRefillPeriodSec = 60
    registerLimit = 100
    registerRefillPeriodSec = 3600
}
